version: "3.3"

services:
  # MySQL
  db:
    container_name: "db"
    build: ./docker/mysql
    restart: always
    tty: true
    environment:
      MYSQL_DATABASE: sample_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - ./log/mysql:/var/log/mysql
    networks:
      - local-net
    # FastAPI
  api:
    links:
      - db
    container_name: "api"
    build: ./docker/api
    ports:
      - "8000:8000"
    volumes:
      - ./app:/usr/src/server
    networks:
      - local-net
  phpmyadmin:
    container_name: "phpmyadmin"
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    depends_on:
      - db
    networks:
      - local-net

networks:
  local-net:
    driver: bridge
