-- -- Inserción de categorías
-- INSERT INTO
--     categories (id, name)
-- VALUES
--     (UUID (), 'FROM USA'),
--     (UUID (), 'Generic Viagra'),
--     (UUID (), 'Generic Soma'),
--     (UUID (), 'Tapentadol'),
--     (UUID (), 'COVID-19'),
--     (UUID (), 'Anti-Depressants');

-- -- Obtención de los UUID generados para las categorías
-- SELECT
--     id,
--     name
-- FROM
--     categories;

-- -- Inserción de productos (Usamos UUID para las categorías)
-- INSERT INTO
--     products (
--         id,
--         name,
--         category_id,
--         price,
--         description,
--         image_url,
--         quantity,
--         availability
--     )
-- VALUES
--     (
--         UUID (),
--         'Tramadol 100mg',
--         (
--             SELECT
--                 id
--             FROM
--                 categories
--             WHERE
--                 name = 'FROM USA'
--         ),
--         3.87,
--         'Tramadol from the USA in 100mg tablets',
--         '/resources/img/products/tramadol100mg.jpg',
--         '100mg',
--         TRUE
--     ),
--     (
--         UUID (),
--         'Viagra 100mg - USA',
--         (
--             SELECT
--                 id
--             FROM
--                 categories
--             WHERE
--                 name = 'FROM USA'
--         ),
--         2.76,
--         'Viagra 100mg imported from USA',
--         '/resources/img/products/viagra100mg.jpg',
--         '100mg',
--         TRUE
--     ),
--     (
--         UUID (),
--         'Viagra 50mg',
--         (
--             SELECT
--                 id
--             FROM
--                 categories
--             WHERE
--                 name = 'Generic Viagra'
--         ),
--         0.73,
--         'Generic Viagra 50mg tablets',
--         '/resources/img/products/viagra50mg.jpg',
--         '50mg',
--         TRUE
--     ),
--     (
--         UUID (),
--         'Soma 350mg',
--         (
--             SELECT
--                 id
--             FROM
--                 categories
--             WHERE
--                 name = 'Generic Soma'
--         ),
--         1.00,
--         'Generic Soma 350mg tablets',
--         '/resources/img/products/soma350mg.jpg',
--         '350mg',
--         TRUE
--     ),
--     (
--         UUID (),
--         'Tapentadol 100mg',
--         (
--             SELECT
--                 id
--             FROM
--                 categories
--             WHERE
--                 name = 'Tapentadol'
--         ),
--         2.26,
--         'Tapentadol 100mg tablets for pain relief',
--         '/resources/img/products/tapentadol100mg.jpg',
--         '100mg',
--         TRUE
--     ),
--     (
--         UUID (),
--         'Hydroxychloroquine Sulphate',
--         (
--             SELECT
--                 id
--             FROM
--                 categories
--             WHERE
--                 name = 'COVID-19'
--         ),
--         1.25,
--         'Hydroxychloroquine Sulphate tablets for COVID-19',
--         '/resources/img/products/hydroxychloroquine.jpg',
--         '200mg',
--         TRUE
--     ),
--     (
--         UUID (),
--         'Duloxetine 20 mg',
--         (
--             SELECT
--                 id
--             FROM
--                 categories
--             WHERE
--                 name = 'Anti-Depressants'
--         ),
--         0.85,
--         'Duloxetine for depression, 20mg',
--         '/resources/img/products/duloxetine20mg.jpg',
--         '20mg',
--         TRUE
--     );